version: '3.8'

services:
  go-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./configs:/app/configs
    restart: always
networks:
  go-backend-network:
    driver: bridge

