// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"vulcan_labs_cinema/internal/controller"
	"vulcan_labs_cinema/internal/services"
)

// Injectors from cinema.wire.go:

func InitCinemaRouterHandler() (*controller.CinemaController, error) {
	iCinemaService := services.NewCinemaService()
	cinemaController := controller.NewCinemaController(iCinemaService)
	return cinemaController, nil
}
